version: '3.8'
services:

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin

  apache:
    image: httpd:latest
    restart: always
    depends_on:
      - phpmyadmin
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/local/apache2/htdocs/

  minetest:
    image: lscr.io/linuxserver/minetest:latest
    container_name: ${PROJECT_NAME}minetest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CLI_ARGS=--gameid minetest --port 25565
    volumes:
      - ./minetest/.minetest:/config/.minetest
    ports:
      - 25565:25565/udp
    restart: unless-stopped
