version: '3.8'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 8181:5432
    environment:
      POSTGRES_PASSWORD: tp12023
      POSTGRES_USER: postgres
      POSTGRES_DB: Ruben
    depends_on:
      - pgadmin

  web89:
    image: php:8.2-apache
    container_name: apache
    volumes:
      - ./web89/html:/var/www/html
    ports:
      - 89:80

  minetest:
    image: lscr.io/linuxserver/minetest:latest
    container_name: ${PROJECT_NAME}minetest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CLI_ARGS=--gameid minetest --port 25565
    volumes:
      - ./minetest/.minetest:/config/.minetest
    ports:
      - 25565:25565/udp
    restart: unless-stopped
